enableGlobalCache: false

enableTelemetry: false

nmMode: hardlinks-global

nodeLinker: pnp

packageExtensions:
  '@mui/x-date-pickers@*':
    dependencies:
      react-dom: '*'
  '@svgr/core@*':
    dependencies:
      '@babel/core': '*'
  chalk@*:
    dependencies:
      '#ansi-styles': 'npm:ansi-styles@*'
      '#supports-color': 'npm:supports-color@*'
  eslint-config-react-app@*:
    dependencies:
      '@babel/plugin-syntax-flow': '*'
      '@babel/plugin-transform-react-jsx': '*'
  material-react-table@*:
    dependencies:
      react-dom: '*'
  material-table@*:
    dependencies:
      '@emotion/react': '*'
  material-ui-popup-state@*:
    dependencies:
      react-dom: '*'
  npm-check-updates@*:
    dependencies:
      ini: '*'
  react-router-dom@*:
    dependencies:
      '@remix-run/router': '*'
  stylelint-config-recommended-scss@*:
    dependencies:
      postcss: '*'
  stylelint-config-xo-scss@*:
    dependencies:
      postcss: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

pnpEnableEsmLoader: true

pnpEnableInlining: true

pnpFallbackMode: dependencies-only

pnpMode: strict

yarnPath: .yarn/releases/yarn-3.2.4.cjs
